ballerina-platform/module-ballerina-regex

- regex-ballerina/build.gradle
> Update ballerina command to bal command
> Update ballerina command to bal command

- regex-ballerina/natives.bal
Related Issue: ballerina-platform/ballerina-lang#28034
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …
> Change the name of the `java` langlib module to `jballerina.java`

- .github/workflows/publish-release.yml
- gradle.properties
> Fix release workflow & update dependencies versions

- .github/workflows/build-master.yml
- .github/workflows/pull-request.yml
- README.md
- regex-ballerina/build.gradle
> Enable publishing of code coverage

- regex-ballerina/build.gradle
> Disable tests when publishing the module

- regex-ballerina/build.gradle
> Renames the extension of the package distribution file from balo to bala 
> Fixes ballerina-platform/ballerina-lang#28476
> Replace balo with bala

- .github/workflows/publish-release.yml
- README.md
- build.gradle
- gradle.properties
- regex-ballerina/Package.md
- regex-ballerina/build.gradle
$subject as well as replacing module with package in MDs.
> Enable publishing to b7a central

- gradle.properties
Reverts ballerina-platform/module-ballerina-regex#13
> Revert "[Automated] Sync main after 0.7.0-alpha2 release"

- gradle.properties
Bringing back changes in https://github.com/ballerina-platform/module-ballerina-regex/pull/13
> Redo reverted PR - [Automated] Sync main after 0.7.0-alpha2 release

- gradle.properties
> Bump ballerina version

- build.gradle
- regex-ballerina/build.gradle
> Re-order Build Tasks to Publish to the Ballerina Central

- regex-ballerina/build.gradle
> Remove native dependency in gradle file

- .github/workflows/pull-request.yml
> Change master to main in yml

- .github/workflows/build-master.yml
- .github/workflows/pull-request.yml
- regex-ballerina/build.gradle
> Remove publishing testable jar and exec artifacts

- README.md
> Add Codecoverage Badge to Readme

- regex-ballerina/build.gradle
> Add extracted bala in the zip artifact
> Fixes ballerina-platform/ballerina-lang#27763
> Add extracted bala in the zip artifact

- regex-ballerina/build.gradle
> Add -c flag to build command
> Related to ballerina-platform/ballerina-lang#29032
> Add -c flag to build command

- build.gradle
- regex-ballerina/build.gradle
> Strip stdlib dependency version

- regex-ballerina/build.gradle
Set flag to enable Jacoco Coverage XML generation. Fixes https://github.com/ballerina-platform/ballerina-lang/issues/30381
> Set flag to enable Jacoco Coverage XML generation

- build-config/checkstyle/build.gradle
- build.gradle
- gradle.properties
- regex-ballerina/build.gradle
Standardize build script of Ballerina module
> Apply Gradle Ballerina plugin for Ballerina module build script

- README.md
- regex-ballerina/Module.md
- regex-ballerina/Package.md
- regex-ballerina/natives.bal
> Improve API Docs

- regex-ballerina/Module.md
> Remove usage of the functions in the Module.md

- regex-ballerina/Package.md
$Subject
Related issue: ballerina-platform/ballerina-standard-library#1462
> Update Package.md links into HTML format

- .github/workflows/build-timestamped-master.yml
- .github/workflows/central-publish.yml
- .github/workflows/publish-release.yml
- .github/workflows/pull-request.yml
$Subject
Related issue:https://github.com/ballerina-platform/ballerina-release/issues/547
> Update GitHub action workflow scripts

- .github/workflows/trivy-scan.yml
$Subject
It hasn't used any check style or spot bug as this is a ballerina package. Hence, task 'check' is ambiguous.
Related to: https://github.com/ballerina-platform/ballerina-standard-library/issues/1849
> Reomve check flag in the trivy build

- gradle.properties
$Subject
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/2396
> Update gradle version

- docs/spec/spec.md
$subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/2323
> Add specification doc

- .github/workflows/publish-release.yml
> Disable release publish to central

- .github/workflows/publish-release.yml
Revoke https://github.com/ballerina-platform/module-ballerina-regex/pull/312
> Re-enable the publish to central

- docs/spec/spec.md
> Add the edition in the specification

- docs/spec/spec.md
> Update the spec

- gradle.properties
> Bump module version to 1.3.0

- .github/workflows/central-publish.yml
- .github/workflows/publish-release.yml
- .github/workflows/trivy-scan.yml
- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
$Subjec
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/2902
> Update Trivy scan-type to enable JAR scanning

- docs/spec/spec.md
> Update the contents and sub-heading style 

- ballerina/natives.bal
$Subject
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/2859
> Add the list of characters the user should escape when defining the delimiter

- .github/workflows/build-with-bal-test-native.yml
- README.md
- examples/build.gradle
- gradle.properties
> Related to : [`Incorporate GraalVM native-image test build to Std Libs daily build #3316`](https://github.com/ballerina-platform/ballerina-standard-library/issues/3316)
> Add Build with bal test native workflow

- ballerina/types.bal
- ballerina/utils.bal
> Change `Groups` object to public

- .github/workflows/pull-request.yml
- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
$Subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/3988
> Add codecov report upload retry step

- README.md
- ballerina/Module.md
- ballerina/Package.md
> Add deprecate message in the API Docs

- ballerina/Module.md
- ballerina/Package.md
Add deprecation notice in blockquotes
> Add deprecation notice in blockquotes

- gradle.properties
> Downgrade the version

- .github/workflows/build-timestamped-master.yml
- .github/workflows/central-publish.yml
- .github/workflows/publish-release.yml
- .github/workflows/pull-request.yml
- .github/workflows/trivy-scan.yml
- gradle.properties
> Update java-version to 17.0.7

- .github/workflows/build-timestamped-master.yml
- .github/workflows/build-with-bal-test-graalvm.yml
- .github/workflows/central-publish.yml
- .github/workflows/publish-release.yml
- .github/workflows/pull-request.yml
- .github/workflows/trivy-scan.yml
- README.md
- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
- build-config/resources/Ballerina.toml
- gradle.properties
> Migrate to Java 21

- .github/workflows/build-timestamped-master.yml
- .github/workflows/central-publish.yml
- .github/workflows/publish-release.yml
- .github/workflows/pull-request.yml
- .github/workflows/trivy-scan.yml
- .github/workflows/update_specs.yml
> Update action versions to `v4`
